### ISSUE TITLE
How to create a new i2c project to stm32f469 discovery kit to see Terminal (Logs)

### ISSUE THREAD

**Issue by neuberfran** [RT-Thread/rt-thread#6234]
Hi,

I have SmartDrive in C++ (to PlatFormIo) AND in Java to Android

https://github.com/neuberfran/SmartDriveEmC
https://github.com/neuberfran/SmartDrive

I need help to transpose this driver to rt-thread/stm32f469 disco kit

I saw it on this site: https://club.rt-thread.org/index.php/ask/question/0d6fd0d49aa2f1af.html
that the I2C1 (Bus) is already used by the screen that comes with the kit, **correct**?

I tried several sites, like the one below:
https://www.rt-thread.io/document/site/rtthread-studio/drivers/soft-i2c/rtthread-studio-soft-i2c/

But I just don't get the **msh>** terminal when I create project in Base On MCU. Only in Base On Board. Why? 

How to solve it?

**Comment by mysterywolf** [comment]
We have fixed this problem. STM32 F469 DISC hardware has two different types with two different touch sensor types. Please follow this video to import the latest code (note latest release version) to RT-Thread Studio. https://www.youtube.com/watch?v=fREPLuh-h8k

**Comment by mysterywolf** [comment]
latest code (not latest release version)

**Comment by neuberfran** [comment]
@mysterywolf Not solved yet. Look pic. The new project named discovery6 not have the drivers folder. I need it to configure i2c2 in board.h file. 

This project (discovery6) looks like this in the same way as before when generating a project using the Base on BOARD option. Being that to appear the drivers folder it is necessary to generate the project by Base on MCU
![not solved yet](https://user-images.githubusercontent.com/38701397/183265490-99d06dd5-e7e9-4a8f-a3eb-ee72c8b24ea5.png)

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/183265684-2acd59fa-d397-489e-89c3-b8a29e3d25bb.png)
![image](https://user-images.githubusercontent.com/34888354/183265698-0ea6448b-dea8-4139-8f84-4133dfdc4cc8.png)
![image](https://user-images.githubusercontent.com/34888354/183265715-4932e285-3fc2-4a22-a1f4-8fff44c004e5.png)
![image](https://user-images.githubusercontent.com/34888354/183265733-97f80030-d19f-4426-a353-64767ed11107.png)

**Comment by neuberfran** [comment]
@mysterywolf How can I will use I2C2 like this:
https://chowdera.com/2022/159/202206080317229229.html

?

**Comment by mysterywolf** [comment]
Then, select the "hammer" to compile the project as well as auto-save the configurations.

**Comment by mysterywolf** [comment]
Not necessary. This buttons can auto-select all of the dependency, like you mentioned, iic and others. By using these buttons, users can one-step configure the board.

**Comment by neuberfran** [comment]
@mysterywolf I have issue here to add lvgl:

../applications/lvgl/lv_port_indev.c:22:20: fatal error: ft6236.h: No such file or directory
compilation terminated.
make: *** [applications/lvgl/subdir.mk:21: applications/lvgl/lv_port_indev.o] Error 1

![image](https://user-images.githubusercontent.com/38701397/183265900-5fa89628-1b87-4467-9692-33627bc0c3bf.png)

**Comment by neuberfran** [comment]
@mysterywolf 
![image](https://user-images.githubusercontent.com/38701397/183266013-39790b36-1623-4233-a231-930f9270ca6a.png)

**Comment by mysterywolf** [comment]
Ohhhmy problem there is a index error in my side. Give me some time

**Comment by mysterywolf** [comment]
Hi please close the RT-Thread Studio and reopen it. Wait for 10 secs, and then right click
![屏幕截图 2022-08-06 171539](https://user-images.githubusercontent.com/34888354/183266282-1786ed5d-ebd8-4700-84e3-790b85d1e3a5.png)
and then compile the project again.

**Comment by neuberfran** [comment]
@mysterywolf Now I want (step to step) to enter smartdrive in msn/> and I will can use My external i2c driver. I talked about it at the beginning of this topic. `[]s

https://github.com/neuberfran/SmartDriveEmC
https://github.com/neuberfran/SmartDrive

**Comment by mysterywolf** [comment]
If you want to export a command, you can follow this branch of code: 
https://github.com/RT-Thread/rt-thread/blob/master/components/finsh/cmd.c#L891-L992
use `MSH_CMD_EXPORT_ALIAS` to export

**Comment by neuberfran** [comment]
@mysterywolf Sorry to insist. I somehow consider myself a beginner. I need to do it step by step:

1) Why did you send me this link? What will I proceed from it?

![i2c address of the smartdrive in 7 and 8 bits](https://user-images.githubusercontent.com/38701397/183271333-bacdc243-4545-45ee-84bf-007542e6d49d.png)
![everything is ready here](https://user-images.githubusercontent.com/38701397/183271336-af654067-abd2-468e-bd8c-0a0ec67132ff.jpg)

**Comment by mysterywolf** [comment]
So you want to add another I2C ?

**Comment by neuberfran** [comment]
@mysterywolf Yes. I have external driver. Photos above.

These links below show that the driver works on esp32/platformio and Java/Android. But I need to make modifications and implementations. Which?

https://github.com/neuberfran/SmartDriveEmC
https://github.com/neuberfran/SmartDrive****

**Comment by mysterywolf** [comment]
https://github.com/neuberfran/SmartDriveEmC This is Arduino library right?

RT-Thread support Arduino API. There is a compatibility layer of Arduino for RT-Thread is called RTduino. and STM32F469 also Support it.
![image](https://user-images.githubusercontent.com/34888354/183271486-678cdd21-1cff-4f65-a89a-aba3391bd8d3.png)


More information please see: https://github.com/RTduino/RTduino#3-arduino%E5%BA%93%E7%9A%84%E5%AF%BC%E5%85%A5%E5%92%8C%E4%BD%BF%E7%94%A8

**Comment by mysterywolf** [comment]
You can directly copy this library to `user` this folder and right click `sync sconscript to project`
![image](https://user-images.githubusercontent.com/34888354/183271551-fc7d0001-25ad-48e9-abe5-50f8e2c070e6.png)

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/183271591-9dbeb849-b344-452e-bfe7-78d22544b53a.png)
There is the setup and loop function

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/tree/master/bsp/stm32/stm32f469-st-disco/applications/arduino_pinout

**Comment by neuberfran** [comment]
@mysterywolf Tks. I stay with issue in this tutorial too(for 2 weeks now):
https://blog.csdn.net/bonson2004/article/details/122040352

In ifconfig part I can see (using ifconfg e0 Not ifconfig Only egual tutorial) 192.168.1.30, etc, etc...But I can't ping to 192.168.1.2. I don't know why. Do u know

![issue111](https://user-images.githubusercontent.com/38701397/183271759-a4e8c152-04cb-4f3f-a038-020dc81ae815.png)

**Comment by mysterywolf** [comment]
You cannot direct connect the network cable with computer and board, you need to use a router.

**Comment by neuberfran** [comment]
@mysterywolf But from what I understand from the tutorial the guy is connecting the ch32v307 directly to his notebook. Not even about DHCP he talked about in the tutorial.

**Comment by mysterywolf** [comment]
He missed. You need to use cross over network cable rather than a normal (straight-through) network cable if you want to directly connect the board with computer; otherwise, you need to use a router.

**Comment by neuberfran** [comment]
@mysterywolf There is something wrong with the programming of the csds project. In this photo below, I connected a red cable to the PC and turned on the switch light. On the other hand, the yellow cable connected to the ch32v307 does not light up anything on the switch. will never **ping.**

![switch](https://user-images.githubusercontent.com/38701397/183300708-9d2d9ce3-4b20-4d06-b0f0-9a643df601aa.jpg)

**Comment by neuberfran** [comment]
> ![image](https://user-images.githubusercontent.com/34888354/183271591-9dbeb849-b344-452e-bfe7-78d22544b53a.png) There is the setup and loop function

Will I be able to use i2c2 with this system (arduino pinout)? (Because i2c1 will already be being used by LVGL

**Comment by mysterywolf** [comment]
if you want to change to i2c2 please change here https://github.com/RT-Thread/rt-thread/blob/master/bsp/stm32/stm32f469-st-disco/applications/arduino_pinout/pins_arduino.h#L48

**Comment by mysterywolf** [comment]
But, you actually can keep i2c1 and just use D14 and D15 like Arduino, because I2c is a bus.

**Comment by neuberfran** [comment]
@mysterywolf I don't know if everything Ok yet. I don't have more folder user(s) afoter I copy SmartDrive.h and SmartDrive.cpp. I copy this files in two places

![I don't know if everything Ok yet](https://user-images.githubusercontent.com/38701397/183307007-89a666d4-63c0-4e89-b01a-0f2b6305cd46.png)
![first part](https://user-images.githubusercontent.com/38701397/183307009-6a83296b-8f1a-4a90-91bf-fb1225639500.png)

**Comment by mysterywolf** [comment]
nop you need to copy the libraries with the folder or directly plug the zip file into the user file. rather two single files.

**Comment by neuberfran** [comment]
@mysterywolf Please. Download the Zip file And show me (with images) What I need do. Will I have the user(s) folder again? Or will I have to create another project from scratch?

https://github.com/neuberfran/SmartDriveEmC

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/183307811-122b578f-5c03-4645-be7b-e50170db18e8.png)
download the zip file and directly drag this zip file into user folder, you don't need to create a project again. After dragging the zip into user folder, you just need to click sync sconscript to project again.

**Comment by neuberfran** [comment]
@mysterywolf  I have issues because Wire.h, etc...etc...

https://gist.github.com/neuberfran/15f9bc9ea6855f238da0ae3a4b72ebaa

![image](https://user-images.githubusercontent.com/38701397/183308070-4142a10f-6b82-423f-b389-09442f75fd20.png)

**Comment by neuberfran** [comment]
@mysterywolf 

I don't have smartdrive in i2c scan results yet. Despite everything connected and motor On

Do I need to create arduino.cpp and main.c files?
![image](https://user-images.githubusercontent.com/38701397/183308164-81936e99-c7b5-4e54-a212-b4af00361fab.png)

**Comment by mysterywolf** [comment]
Please make sure your library is correct. This warnings comes from your library. Wire.h has been test through other arduino libraries successfully. 

Cearly, you didn't create the i2c2 bus device successfully. So arduino cannot use i2c2. I suggest you to use i2c1 bus, it has been initiated successfully.

**Comment by mysterywolf** [comment]
> Do I need to create arduino.cpp and main.c files?

Nop , there is a arduino_main.cpp in application folder.

**Comment by mysterywolf** [comment]
Serial.begin(); will be better rather than Serial.begin(9600);
Serial.begin(); means console serial will follow the rt-thread configurations which is 115200 by default.

**Comment by neuberfran** [comment]
@mysterywolf I've been using i2c1 since the first moment. I still haven't been successful. Disregard what I showed about previous issues and Wire.h. I had put the SmartDrive.cpp in the wrong place(applications). I don't get compilation errors. I need to see how to debug or find the runtime error

**Comment by mysterywolf** [comment]
Yap, please make sure your library is correct. Because Wrie.h has been tested under several arduino libraries.

**Comment by neuberfran** [comment]
@mysterywolf 

Hey. With this code(arduino_main.cpp), I don't have more msh/> here. WhY? Because Serial.begin(9600)?

```

#include <Arduino.h>
#include <SmartDrive.h>

SmartDrive smd = SmartDrive(SmartDrive_DefaultAddress);

void setup(void)
{
    /* put your setup code here, to run once: */
/*  pinMode(LED_BUILTIN, OUTPUT); */
    Serial.begin(9600);
}

void loop(void)
{
    /* put your main code here, to run repeatedly:
    digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
    delay(100);*/

    Serial.print("Motor powered: " + smd.IsMotorPowered(SmartDrive_Motor_ID_1));
    delay(1000);
}

```

![image](https://user-images.githubusercontent.com/38701397/183309046-7f2c33d7-5e55-4f5a-ac94-3a6e0ad6a598.png)

**Comment by mysterywolf** [comment]
Yes, because RT-Thread default is 115200 and now you change to 9600.. of course it will not show any information if you keep using the terminal with 115200. So that I suggested you to use Serail.begin()

**Comment by neuberfran** [comment]
@mysterywolf Motor powered: show nothing...

![image](https://user-images.githubusercontent.com/38701397/183309401-0d7eeb33-abb9-498b-85de-83922d67fc50.png)

**Comment by neuberfran** [comment]
@mysterywolf 
![image](https://user-images.githubusercontent.com/38701397/183309485-face5197-a85d-4e50-974e-c84239cfd376.png)

**Comment by mysterywolf** [comment]
try to move SmartDrive() into setup function

**Comment by neuberfran** [comment]
@mysterywolf Not Solved Yet. I will test in esp32 dev kit now. Although I already used this lib last week. Only it was on ubuntu 22.04/VsCode/PlatformIo

**Comment by neuberfran** [comment]
@mysterywolf With esp32 I can run motor 1 with delay(5000);. I'm not put zip file. But I put smartdrive.cpp and smartdrive.h in folder Lib. I think..I stay using platformIo/ArduinoProject/VsCode

https://youtu.be/IEpiTdXtcsw

**Comment by mysterywolf** [comment]
> I'm not put zip file. But I put smartdrive.cpp and smartdrive.h in folder Lib.

I fix this problem at here: https://github.com/RTduino/RTduino/commit/53dfa0aea0592ec70b1fc9fa61b9d9d677aa5227
> I think..I stay using platformIo/ArduinoProject/VsCode
Sorry for that. I cannot provide further support. Because I don't have the real hardwire or something like that. I have tested the Arduino UNO I2C libraries. Maybe still needs to be tested.

**Comment by neuberfran** [comment]
@mysterywolf I'm pretty sure the problem is with regards to using i2c1. What do you say about it? Since I'm going to use i2c1 for lvgl

**Comment by mysterywolf** [comment]
You may try to create a new project and only enable Arduino. Don't enable LVGL. Try it again.

**Comment by neuberfran** [comment]
> I fix this problem at here

Ok. But inside de Zip folder have src folder and after have SmartDrive.h and SmartDrive.cpp

![image](https://user-images.githubusercontent.com/38701397/183311374-335bf66d-2f63-4afa-b80d-6681d39f2e5e.png)

**Comment by neuberfran** [comment]
> You may try to create a new project and only enable Arduino. Don't enable LVGL. Try it again.

Ok. I will do

**Comment by mysterywolf** [comment]
IN this time, you can directly put these two single files in user folder, if you create a new project.

**Comment by neuberfran** [comment]
@mysterywolf Not solved yet with Zip(Without LVGL). I change jumper wire from Vin to 5v. Because my external driver (SmartDrive) Work's with 5v. But nov solved

**Comment by neuberfran** [comment]
> IN this time, you can directly put these two single files in user folder, if you create a new project.

I will try this

**Comment by neuberfran** [comment]
@mysterywolf Sorry. I solve here. I have 2 i2c1 devices Now. 
I was connecting sda/scl on a5/a4 => pb8/pb9 and not on d15/d14. I connected to 5v

![image](https://user-images.githubusercontent.com/38701397/183313276-dfe424ad-1c52-40bd-b7f6-bde4733f9188.png)

**Comment by mysterywolf** [comment]
Ohhh
You need to read my reply and documents carefully...
![image](https://user-images.githubusercontent.com/34888354/183313377-2a7fb969-4779-4c07-b0f6-507c178a9afc.png)
![image](https://user-images.githubusercontent.com/34888354/183313395-e7631a60-718e-4c13-8e49-93c50c0afb24.png)
![image](https://user-images.githubusercontent.com/34888354/183313402-50dde458-7d54-42df-ac8e-d7e4ae8e8e98.png)

**Comment by neuberfran** [comment]
@mysterywolf I need tips, links, tutorials, videos on linking a design (photo below) made in LVGL with the above mentioned codes (main.c, arduino_main.cpp). That way I can give commands to my motor that is linked to the external i2c driver:

![croki](https://user-images.githubusercontent.com/38701397/183557731-521acfb0-6dc4-47c4-8201-9a8ed11c4323.jpg)

**Comment by mysterywolf** [comment]
please go to LVGL community to ask this question.

www.lvgl.io

**Comment by neuberfran** [comment]
@mysterywolf Pls. Help-me. I can't generate project.vcxproject Here. I have vs2019 and vs2022 community. Scons version is 3.0.5
![image](https://user-images.githubusercontent.com/38701397/183791054-3eaefbf0-f878-496d-9d80-fa4e253ec196.png)

**Comment by mysterywolf** [comment]
https://youtu.be/k7QYk6hSwnc?t=1003

**Comment by neuberfran** [comment]
@mysterywolf I stat trying this But I have issues in scons --target=vs2019(command). Look a last pic bro Pls

**Comment by mysterywolf** [comment]
Please click that link and watch the video carefully.

**Comment by neuberfran** [comment]
@mysterywolf My english is not very good yet. Only work's in vs2012?

**Comment by mysterywolf** [comment]
please use scons --target=vs2012 to generate a VS2012 project and open this project by using VS2022 or VS2019 then the VS will tell you that you need to upgrade you project then click yes button.

**Comment by neuberfran** [comment]
@mysterywolf 

I got the same error I had when I used vs2019

> scons --target=vs2012
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\rt-thread-master\bsp\simulator\SConstruct", line 13, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\rt-thread-master\bsp\simulator\SConstruct", line 15, in <module>
No vc version!

![image](https://user-images.githubusercontent.com/38701397/183796144-269cfdd7-1e0b-44dd-a9e6-1c59de78e364.png)

**Comment by mysterywolf** [comment]
try to comment out this line and try again https://github.com/RT-Thread/rt-thread/blob/master/bsp/simulator/rtconfig.py#L40
if this works, please tell me.

**Comment by mysterywolf** [comment]
sorry this: https://github.com/RT-Thread/rt-thread/blob/master/bsp/simulator/rtconfig.py#L34

**Comment by neuberfran** [comment]
scons --target=vs2012
scons: Reading SConscript files ...

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\rt-thread-master\bsp\simulator\SConstruct", line 13, in <module>

scons: warning: No version of Visual Studio compiler found - C/C++ compilers most likely not set correctly
File "C:\rt-thread-master\bsp\simulator\SConstruct", line 15, in <module>
No vc version!
UnsupportedVersion: Unknown version :
  File "C:\rt-thread-master\bsp\simulator\SConstruct", line 80:
    objs = PrepareBuilding(env, RTT_ROOT, has_libcpu=False)
  File "C:\rt-thread-master\tools\building.py", line 204:
    utils.ReloadModule(rtconfig)
  File "C:\rt-thread-master\tools\utils.py", line 293:
    reload(module)
  File "C:\rt-thread-master\bsp\simulator\rtconfig.py", line 37:
    EXEC_PATH = SCons.Tool.MSCommon.vc.find_vc_pdir(vc_version)
  File "C:\env\tools\ConEmu\ConEmu\..\..\..\tools\Python27\Lib\site-packages\scons\SCons\Tool\MSCommon\vc.py", line 351:
    raise UnsupportedVersion("Unknown version %s" % msvc_version)

![image](https://user-images.githubusercontent.com/38701397/183798444-f992af7f-0916-4b01-9242-3573667adcfe.png)

**Comment by mysterywolf** [comment]
I don't know how you installed the VS. The Scons cannot find the path of the VS in your computer. Do you install the Visual Studio correctly？

**Comment by neuberfran** [comment]
@mysterywolf I stay trying putting windows 10 sdk and windows 11 sdk in my vs2019 and vs2022

**Comment by neuberfran** [comment]
@mysterywolf mY VS2019 not have any things about c++
![image](https://user-images.githubusercontent.com/38701397/183806557-63597c6a-4c64-4a17-9a07-1e2e7f0b8193.png)

**Comment by neuberfran** [comment]
@mysterywolf I think I need upgrade scons to 3.1.x (Here 3.0.5), VS2019, Python3

https://github.com/godotengine/godot/issues/28152

**Comment by mysterywolf** [comment]
https://drive.google.com/file/d/1fjR8Q-Sw7XC5eRFTxRqF4aCHDHWFBXDY/view?usp=sharing
You may try this. This is the new version of ENV

**Comment by neuberfran** [comment]
@mysterywolf Not solved yet with scons 3.1.1

![image](https://user-images.githubusercontent.com/38701397/183965207-675e7e68-1825-49ec-8cb1-eb86e7e4010a.png)

**Comment by mysterywolf** [comment]
Maybe you can try the simulator with QEMU. https://youtu.be/k7QYk6hSwnc?t=463

**Comment by neuberfran** [comment]
@mysterywolf I have issue to install vs2012 here:

![image](https://user-images.githubusercontent.com/38701397/183973668-78cd36ab-6d6a-43da-a7bb-4dbf254db9e2.png)

**Comment by neuberfran** [comment]
@mysterywolf No I have visual studio file. But I can't open yet in vs2019. I stay installing vs2022

![image](https://user-images.githubusercontent.com/38701397/183975546-fa1b5e43-c546-4d0a-8276-cd0e65f488a8.png)

**Comment by neuberfran** [comment]
@mysterywolf I can't open project.vcxproj in VS2019 and VS2022. As I mentioned above, I could not install vs2012 on this PC with w11. But the command used to create the project.vcxproj was: scons --target=vs2012

![image](https://user-images.githubusercontent.com/38701397/183981452-12a53881-0074-4f6c-8053-19fbb7f9e0c9.png)

**Comment by mysterywolf** [comment]
I don't know why you PC cannot find the path of VS. I submit a PR to skip this step. I have tested. You can try it.
https://github.com/RT-Thread/rt-thread/pull/6246

**Comment by mysterywolf** [comment]
You don't need to install Vs2012. VS2022 or VS2019 is good. Just I mentioned, after scons generate a VS project. VS will help you to upgrade from 2012 to 2019 or 2022. VS2019 or 2022 can open the VS2012 project which scons generated.

**Comment by neuberfran** [comment]
@mysterywolf In other pc (note) with windows 10 and vs2012 I can update project to vs2012. But I have 1 issue to build:

![image](https://user-images.githubusercontent.com/38701397/183997280-88860c72-68af-4d33-a7b1-a9406e8fcc7a.png)

**Comment by mysterywolf** [comment]
do you forget to select the enable demo? or forget to download the software package by pkgs --update



---Original---
From: "Neuber ***@***.***&gt;
Date: Wed, Aug 10, 2022 15:08 PM
To: ***@***.***&gt;;
Cc: "Man, Jianting ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] How to create a new i2c project tostm32f469 discovery kit to see Terminal (Logs) (Issue #6234)




 
@mysterywolf In other pc (note) with windows 10 and vs2012 I can update project to vs2012. But I have 1 issue to build:

**Comment by neuberfran** [comment]
@mysterywolf 

![screen1](https://user-images.githubusercontent.com/38701397/184003574-01ea6652-921d-46ef-af9a-a7e98a2f2440.png)

![screen2](https://user-images.githubusercontent.com/38701397/184003603-1b4d87a5-197a-4bc6-a4da-27d4333caf32.png)

**I think the word Download...here is missing. I do not know why**

**Comment by neuberfran** [comment]
> do you forget to select the enable demo? or forget to download the software package by pkgs --update
> […](#)
> ---Original--- From: "Neuber ***@***.***&gt; Date: Wed, Aug 10, 2022 15:08 PM To: ***@***.***&gt;; Cc: "Man, Jianting ***@***.******@***.***&gt;; Subject: Re: [RT-Thread/rt-thread] How to create a new i2c project tostm32f469 discovery kit to see Terminal (Logs) (Issue #6234) @mysterywolf In other pc (note) with windows 10 and vs2012 I can update project to vs2012. But I have 1 issue to build: — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

I'm sure I did. I press ESC and it seems to save Ok. the .config file. But the word Download does not appear....(As it appears in the video)

**Comment by mysterywolf** [comment]
in the video i had used menuconfig -s command to set auto download. but this is a new computer so you need to use menuconfig -s to set. select the auto download option. and cancel downloading from mainland china option. then try again.



---Original---
From: "Neuber ***@***.***&gt;
Date: Wed, Aug 10, 2022 15:29 PM
To: ***@***.***&gt;;
Cc: "Man, Jianting ***@***.******@***.***&gt;;
Subject: Re: [RT-Thread/rt-thread] How to create a new i2c project tostm32f469 discovery kit to see Terminal (Logs) (Issue #6234)




 
@mysterywolf
 

 

 
I think the word Download...here is missing. I do not know why

**Comment by mysterywolf** [comment]
![image](https://user-images.githubusercontent.com/34888354/184007539-56b35ca4-51c5-4034-a802-bf5cf3ac1b46.png)

**Comment by neuberfran** [comment]
> in the video i had used menuconfig -s command to set auto download. but this is a new computer so you need to use menuconfig -s to set. select the auto download option. and cancel downloading from mainland china option. then try again.
> […](#)
> ---Original--- From: "Neuber ***@***.***&gt; Date: Wed, Aug 10, 2022 15:29 PM To: ***@***.***&gt;; Cc: "Man, Jianting ***@***.******@***.***&gt;; Subject: Re: [RT-Thread/rt-thread] How to create a new i2c project tostm32f469 discovery kit to see Terminal (Logs) (Issue #6234) @mysterywolf I think the word Download...here is missing. I do not know why — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


Where I cancel downloading from mainland china option?
![image](https://user-images.githubusercontent.com/38701397/184007887-3abef5ed-3282-40a0-8747-ccb99e90c5cf.png)

**Comment by mysterywolf** [comment]
Yes current setting is great. Then save it. Then use command pkgs --force-upgrade to upgrade the index of software packages.

**Comment by mysterywolf** [comment]
obviously, The LVGL software package did not download successfully. Use pkgs --update to download it.

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/blob/master/documentation/quick-start/quick_start_qemu/quick_start_qemu_linux.md

**Comment by mysterywolf** [comment]
By the way, I am not sure LVGL music demo can run under ubuntu very well. I did not test it before

**Comment by neuberfran** [comment]
> obviously, The LVGL software package did not download successfully. Use pkgs --update to download it.

**Obviously I had already tried pkgs --update**. But I'm not have pkgs here. I don't know why

neuuberfran@ubuntu2004:~/rt-thread/bsp/qemu-vexpress-a9$ **pkgs --update**

Command 'pkgs' not found, did you mean:

  command 'pags' from deb heimdal-clients (7.7.0+dfsg-1ubuntu1)
  command 'pigs' from deb pigpio-tools (1.68-4)

Try: sudo apt install <deb name>

neuuberfran@ubuntu2004:~/rt-thread/bsp/qemu-vexpress-a9$ **pwd
/home/neuuberfran/rt-thread/bsp/qemu-vexpress-a9**

**Comment by neuberfran** [comment]
> By the way, I am not sure LVGL music demo can run under ubuntu very well. I did not test it before

Start to download package : b'' 
(issue)

![Screenshot from 2022-08-10 17-27-52](https://user-images.githubusercontent.com/38701397/184013775-faebce3f-6241-4d1f-bdad-40e8b089b4db.png)

**Comment by mysterywolf** [comment]
> Start to download package : b''

Please use pkgs --upgrade to fix this downlaod failed problem.

Sorry I don't know how to answer this problem.

**Comment by neuberfran** [comment]
> pkgs --upgrade

pkgs --force-upgrade
(issue)
![issue in pkgs update force command in windows 10](https://user-images.githubusercontent.com/38701397/184016302-9dd4950b-850b-4cc8-8c4c-1091cdb74aed.png)

**Comment by neuberfran** [comment]
@mysterywolf  I run pkgs --update in windows 10 And Works.

But issue in vs2012 not solved yet.:

![screen4](https://user-images.githubusercontent.com/38701397/184016437-b1dc5e7d-0d9a-40cd-b60a-b1920c2b9c36.png)

![screen5](https://user-images.githubusercontent.com/38701397/184016461-5e96053c-818d-4e99-a464-43e5d3da4cef.png)

**Comment by mysterywolf** [comment]
pkgs --upgrade then pkgs --force-upgrade

**Comment by neuberfran** [comment]
@mysterywolf 
![image](https://user-images.githubusercontent.com/38701397/184018072-bae9f20d-e3c9-48d9-b212-7065267b1187.png)

**Comment by neuberfran** [comment]
@mysterywolf 

Hi. I'm pretty worried. I'm in the contest and I need 1 mvp and 1 project video on Github by 2022-08-15. I need your help to integrate main.c and arduino_main.cpp with the di lvgl sources:

https://forum.lvgl.io/t/how-to-integrate-rt-thread-i2c-lvgl-project-to-lvgl-design-screen-using-rt-thread-studio-ide/9550/2

**Comment by neuberfran** [comment]
@mysterywolf In vs2022 I have issue:
![screen6](https://user-images.githubusercontent.com/38701397/184046060-2cfa2792-5558-4376-9f54-333b2a10fbb3.png)

**Comment by neuberfran** [comment]
@mysterywolf Work's in windows 10 with windows 10 sdk
![20220810_225755](https://user-images.githubusercontent.com/38701397/184052653-0fbfaafb-726a-46a1-849a-3d6092f5d59c.jpg)

**Comment by neuberfran** [comment]
> @mysterywolf
> 
> Hi. I'm pretty worried. I'm in the contest and I need 1 mvp and 1 project video on Github by 2022-08-15. I need your help to integrate main.c and arduino_main.cpp with the lvgl sources:
> 
> https://forum.lvgl.io/t/how-to-integrate-rt-thread-i2c-lvgl-project-to-lvgl-design-screen-using-rt-thread-studio-ide/9550/2

@mysterywolf kisvegabor (Gabor Kiss-Vamosi) It spoke and I threw the ui files to ui folder.  As shown at the end of this video: https://www.youtube.com/watch?v=6uKf5Bj0xcc

And now ? How to throw these files into RT-THREAD IDE/OS and make the function calls?

![image](https://user-images.githubusercontent.com/38701397/184267804-351e86ba-0a77-42e3-a020-877bc99e05a3.png)

**Comment by mysterywolf** [comment]
if your ENV pkgs --update doesn't work, please follow these commands, type them one by one:

pkgs --upgrade
pkgs --force-upgrade
pkgs --upgrade-modules

**Comment by neuberfran** [comment]
@mysterywolf **Issue here in third command**:

pkgs --upgrade-modules
usage: env.py [-h] [-v] {system,menuconfig,package} ...
env.py: error: unrecognized arguments: --upgrade-modules

![image](https://user-images.githubusercontent.com/38701397/184436656-00f55bda-1495-4f57-a934-d7ee45a3fb80.png)

**Comment by mysterywolf** [comment]
pkgs --force-upgrade 
first then pkgs --upgrade-modules

**Comment by neuberfran** [comment]
@mysterywolf No Solved Yet. And **scons --target=vs2012** not run More. I don't know Why (I have only vs2022 in this machine with windows 11/ windows sdk 10 (I can't upgrade to sdk 11 in vs2022(despite the fact that windows sdk 11 is installed)

![image](https://user-images.githubusercontent.com/38701397/184438671-ba6e3715-716a-4209-928e-4a60b21d98d3.png)

**Comment by mysterywolf** [comment]
https://github.com/RT-Thread/rt-thread/pull/6246 when this PR merged, it will be solved.

**Comment by neuberfran** [comment]
@mysterywolf 

This issue insists on appearing in every project I start:
![screen101](https://user-images.githubusercontent.com/38701397/184504359-f4f92eb3-f1d8-4c84-94d9-0fd9be1cf61e.png)
![screen102](https://user-images.githubusercontent.com/38701397/184504361-77a843c0-6500-42a4-a97a-f1604cd01745.png)
